services:

  nginx:
    depends_on:
      - wordpress
    build: ./requirements/nginx
    image: nginx:42
    container_name: nginx
    restart: always
    ports:
      - 443:443
    networks:
      - inception
    volumes:
      - wp-files:/var/www/html:ro

  wordpress:
    depends_on:
      - mariadb
      - redis
    build: ./requirements/wordpress
    image: wordpress:42
    container_name: wordpress
    restart: always
    networks:
      - inception
    env_file: .env
    volumes:
      - wp-files:/var/www/html

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:42
    container_name: mariadb
    restart: always
    networks:
      - inception
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql

  redis:
    build: ./requirements/bonus/redis
    image: redis:42
    container_name: redis
    restart: always
    networks:
      - inception

  ftp:
    depends_on:
      - wordpress
    build: ./requirements/bonus/ftp
    image: ftp:42
    container_name: ftp
    restart: always
    ports:
      - "21:21"
      - "50000-50100:50000-50100"
    env_file: .env
    networks:
      - inception
    volumes:
      - wp-files:/home/$FTP_USER/ftp/files

  adminer:
    depends_on:
      - mariadb
    build: requirements/bonus/adminer
    image: adminer:42
    container_name: adminer
    restart: always
    networks:
      - inception

  # website:
  #   depends_on:
  #     - nginx
  #   build: requirements/bonus/website
  #   image: website
  #   container_name: website
  #   networks:
  #     - inception

  portainer:
    build: ./requirements/bonus/portainer
    image: portainer:42
    container_name: portainer
    restart: always
    networks:
      - inception
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

networks:
  inception:
    driver: bridge

volumes:
  db-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/olaaroub/data/mariadb'

  wp-files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/olaaroub/data/wordpress'

  portainer-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/olaaroub/data/portainer'