version: '3.8'

services:
  db:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    networks:
      - inception
    env_file: .env
    volumes:
      - data-db:/var/lib/mysql

networks:
  inception:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      o: bind
      device: '/home/olaaroub/data/mariadb'
