# webserv-app.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserv-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webserv
  template:
    metadata:
      labels:
        app: webserv
    spec:
      containers:
      - name: webserv-container
        image: olaaroub/webserv-test:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: webserv-service
spec:
  type: NodePort
  selector:
    app: webserv
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080